spring:
    datasource:
        url: jdbc:mysql://localhost:3306/travelworld?useSSL=false
        username: root
        password:
    jpa:
        properties:
            hibernate:
                dialect:  org.hibernate.dialect.MySQL5InnoDBDialect
                ddl-auto: update

bezkoder:
    app:
        jwtCookieName: bezkoder
        jwtSecret: bezKoderSecretKey
        jwtExpirationMs: 86400000

external:
    api:
        url: https://atravel-api.herokuapp.com/api/

web:
  cors:
    allowed-origins: "http://localhost:4200"
    allowed-methods: GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD
    max-age: 3600
    allowed-headers: "*"
    exposed-headers: "X-Get-Header"